apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: pepsico-cloud-market-place
  title: Pepsico Cloud Market Place
  description: Create a record in ServiceNow on cmp table
  tags:
    - service-now
    - pepsico
    - cloud-market-place
spec:
  owner: rhdh
  type: service
  

  parameters:
    - title: Provide Name Entry for snow table
      required:
        - pepiscoemployeename
      properties:
        snowName:
          title: Requester Name
          type: string      
  steps:
    - id: snowcreate
      name: Snow
      action: servicenow:now:table:createRecord
      input:
        tableName: u_employeename
        requestBody: {
          u_name: "${{ parameters.employeeName }}"
        }
        
  output:
    text:
    - title: Name Field
      content: Entered Name "${{ parameters.snowName }}"
    - title: SysID
      content: Create record with this ID "${{ steps.snowcreate.output.sys_id }}"
