apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: pepsico-cloud-market-place
  title: Pepsico Cloud Market Place 1.1
  description: Create a record in ServiceNow on cmp table
  tags:
    - service-now
    - pepsico
    - cloud-market-place
spec:
  owner: rhdh
  type: service
  

  parameters:
    - title: Provide Name Entry for snow table 
      required:
        - employeename
      properties:
        employeename:
          title: Requester Name
          type: string      
  steps:
    - id: accessallow
      name: Snow
      action: servicenow:now:table:createRecord
      input:
        tableName: u_employeename
        requestBody: {
          u_name: "${{ parameters.employeename }}"
        }
        
  output:
    text:
    - title: Name Field
      content: Entered Name "${{ parameters.employeename }}"
    - title: SysID
      content: Create record with this System ID "${{ steps.allowaccess.output.sys_id }}"
