apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: pepsico-dev-template
  title: Pepsico Dev Flow template 1.4
  description: The Pepsico Dev Flow
  tags:
    - service-now
    - pepsico
    - pepsico-dev-flow
    - argocd
    - azuredevops
    - tekton
    - sonarqube
spec:
  owner: pepsico
  type: service
  

  parameters:
    - title: Provide Name Entry for snow table 
      required:
        - approval
      properties:
        employeename:
          title: Approval ID
          type: string     
  steps:
    - id: snowretrieve
      name: Snow
      action: servicenow:now:table:retrieveRecord
      input:
        tableName: u_employeename
        requestBody: {
          sysId: "${{ parameters.approval }}"
        }
        
  output:
    text:
    - title: Name Field
      content: Retrieve Record
    - title: Service Now Approval Code
      content: Flow Approved with this code ID "${{ steps.snowretrieve.output.sys_id }}"
      
        
       
