apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: pepsico-dev-template
  title: Pepsico Dev Flow template 1.0
  description: Create a record in ServiceNow on pessoa table
  tags:
    - service-now
    - pepsico
    - pepsico-dev-flow
    - argocd
    - azuredevops
    - tekton
    - sonarqube
spec:
  owner: pepsico
  type: service
  

  parameters:
    - title: Service Now SSYD to Retrieve the approval 
      required:
        - snowSysid
      properties:
        snowName:
          title: Service Now System ID
          type: string      
  steps:
    - id: snowretrieve
      name: Snow
      action: servicenow:now:table:retrieveRecord
      input:
        tableName: u_employeename
        requestBody: {
          sys_id: "${{ parameters.snowSysid }}"
        }
        
  output:
    text:
    - title: Name Field
      content: Retrieve Record
    - title: SysID
      content: Create record with this ID "${{ steps.snowcreate.output.sys_id }}"
      
        
       
