apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: pepsico-dev-template
  title: Pepsico Dev Flow template 1.1
  description: The Pepsico Dev Flow
  tags:
    - service-now
    - pepsico
    - pepsico-dev-flow
    - argocd
    - azuredevops
    - tekton
    - sonarqube
spec:
  owner: pepsico
  type: service
  

  parameters:
    - title: Service Now Approval Code
      required:
        - snowsysid1
      properties:
        snowName:
          title: Service Now Approval Code
          type: string      
  steps:
    - id: snowretrieve
      name: Snow
      action: servicenow:now:table:retrieveRecord
      input:
        tableName: u_employeename
        requestBody: {
          sys_id: "${{ parameters.snowsysid1 }}"
        }
        
  output:
    text:
    - title: Name Field
      content: Retrieve Record
    - title: Service Now Approval Code
      content: Flow Approved with this code ID "${{ steps.snowretrieve.output.sys_id }}"
      
        
       
