apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: pepsico-dev-template
  title: Pepsico Dev Flow template
  description: Create a record in ServiceNow on pessoa table
  tags:
    - service-now
    - vijays-embedded-services
spec:
  owner: rhdh
  type: service
  

  parameters:
    - title: Provide Name Entry for snow table
      required:
        - snowName
      properties:
        snowName:
          title: Requester Name
          type: string      
  steps:
    - id: snowcreate
      name: Snow
      action: servicenow:now:table:createRecord
      input:
        tableName: u_pessoa
        requestBody: {
          u_namename: "${{ parameters.snowName }}"
        }
        
  output:
    text:
    - title: Name Field
      content: Entered Name "${{ parameters.snowName }}"
    - title: SysID
      content: Create record with this ID "${{ steps.snowcreate.output.sys_id }}"
      
        
       
