apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: pepsico-dev-template
  title: Pepsico Dev Flow template 3.4
  description: The Pepsico Dev Flow
  tags:
    - service-now
    - pepsico
    - pepsico-dev-flow
    - argocd
    - azuredevops
    - tekton
    - sonarqube
spec:
  owner: rhdh
  type: service
  

  parameters:
    - title: Provide Dev Flow Variables 
      required:
        - approvalcode
        - component_id
      properties:
        approvalcode:
          title: Service Now Approval Code
          type: string 
        component_id:
          title: Application Project Name
          type: string 
        artifact_id:
          title: Artifact Id
          type: string
          default: pepsico-app
          description: Maven Artifact Id
        group_id:
          title: Group Id
          type: string
          default: pepsico-mvn
          description: Maven Group Id
        java_package_name:
          title: Package Name
          default: com.pepsico
          type: string
          description: Name for the package. eg (com.pepsico.blah)
        description:
          title: Description
          type: string
          description: Help others understand what this website is for.
          default: A pepsico app
    - title: Provide Image Registry Information
      required:
        - image_registry
      properties:
        image_registry:
          title: Image Registry
          type: string
          enum:
            - Openshift
            - Quay
            - JFrog
      dependencies:
        image_registry:
          oneOf:
          - properties:
              image_registry:
                 enum:
                   - Openshift
              image_host:
                title: Image Host
                type: string
                description: Host for storing image
                default: image-registry.openshift-image-registry.svc:5000
              image_tag:
                title: Image Tag
                default: latest             
                type: string
                description: Build Image tag
          - properties:
              image_registry:
                  enum:
                    - Quay
              image_host:
                 title: Image Host
                 type: string
                 description: Host for storing image
                 default: quay-b5hxl.apps.cluster-b5hxl.b5hxl.sandbox1689.opentlc.com
              image_organization:
                 title: Organization
                 type: string
                 description: Name of the Quay Organization
                 default: quayadmin
              image_tag:
                 title: Image Tag
                 default: latest
                 type: string
                 description: Build Image tag
          - properties:
              image_registry:
                 enum:
                  - JFrog
              image_host:
                 title: Image Host
                 type: string
                 description: Host for storing image
                 default: jfrog-b5hxl.apps.cluster-b5hxl.b5hxl.sandbox1689.opentlc.com  
              image_organization:
                 title: Organization
                 type: string
                 description: Name of the JFrog Organization
                 default: jfrogadmin
              image_tag:
                 title: Image Tag
                 default: latest
                 type: string
                 description: Build Image tag
    - title: Application repository Information
      required:
        - repo
      properties:
        repo:
          title: Repository Location
          type: object
          properties:
            host:
              title: Repo Host
              type: string
              description: Your SCM host
              default: gitlab-gitlab.apps.cluster-b5hxl.b5hxl.sandbox1689.opentlc.com
              enum:
                - gitlab-gitlab.apps.cluster-b5hxl.b5hxl.sandbox1689.opentlc.com
            owner:
              title: Repo Owner
              type: string
              description: Your SCM host organization/group
              default: development
              enum:
                - development
    - title: Pipeline Selection
      required:
        - pipeline
      properties:
        pipeline:
          title: Pick Your Project's Pipeline
          type: string
          enum:
            - AzureDevOps
            - Tekton
            
            
         


  steps:
    - id: snowretrieve
      name: Snow
      action: servicenow:now:table:retrieveRecord
      input:
        tableName: u_employeename
        sysId: "${{ parameters.approvalcode }}"
    - id: template
      name: Fetch Skeleton + Template
      action: fetch:template
      input:
        url: ./skeleton
        copyWithoutTemplating:
          - .github/workflows/*
        values:
          component_id: ${{ parameters.component_id }}
          description: ${{ parameters.description }}
          namespace: ${{ parameters.component_id }}-dev
          group_id: ${{ parameters.group_id }}
          artifact_id: ${{ parameters.artifact_id }}
          java_package_name: ${{ parameters.java_package_name }}
          owner: ${{ user.entity.metadata.name }}
          cluster: .apps.cluster-b5hxl.b5hxl.sandbox1689.opentlc.com
          host: ${{ parameters.repo.host }}
          destination: ${{ parameters.repo.owner }}/${{ parameters.component_id }}
          quay_destination: ${{ parameters.image_organization}}/${{ parameters.component_id }}
          port: 8080
          verify_commits: ${{ parameters.repo.verify_commits }}

    - id: publish
      name: Publish
      action: roadiehq:utils:sleep
      input:
        amount: 1

    - id: register
      name: Register
      action: roadiehq:utils:sleep
      input:
        amount: 1

    - id: template-gitops-deployment
      name: Generating Deployment Resources
      action: fetch:template
      input:
        url: ./manifests
        copyWithoutTemplating: []
        values:
          component_id: ${{ parameters.component_id }}
          description: ${{ parameters.description }}
          destination: https://${{ parameters.repo.host }}/${{ parameters.repo.owner }}/${{parameters.component_id}}-gitops.git
          source_repository: https://${{ parameters.repo.host }}/${{ parameters.repo.owner }}/${{parameters.component_id}}.git
          repository_name: ${{parameters.component_id}}
          git_owner: ${{ parameters.repo.owner }}
          cluster: .apps.cluster-b5hxl.b5hxl.sandbox1689.opentlc.com
          namespace: ${{ parameters.component_id }}-dev
          image_registry: ${{ parameters.image_registry }}
          image_host: ${{ parameters.image_host }}
          image_organization: ${{ parameters.image_organization }}
          image_name: ${{ parameters.component_id }}
          image_tag: ${{ parameters.image_tag }}
          port: 8080
          repository_host: ${{ parameters.repo.host }}
          deployment_name: quarkus-template
          user: ${{ user.entity.metadata.name }}
          verify_commits: ${{ parameters.repo.verify_commits }}
        targetPath: ./tenant-gitops

    - id: publish-gitops
      name: Publishing to Resource Repository
      action: roadiehq:utils:sleep
      input:
        amount: 1
    - id: create-argocd-resources
      name: Creating argocd resources
      action: roadiehq:utils:sleep
      input:
        amount: 1

    - id: provison pipeline
      name: Provision Pipeline - "${{ parameters.pipeline }}"
      action: roadiehq:utils:sleep
      input:
        amount: 1



    
        
        
  output:
    text:
    - title: Service Now Approval Code
      content: Flow Approved with this code ID $${{ steps.snowretrieve.output.result.sys_id }}
      
        
       

