apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: snow-create-template
  title: Service Now template
  description: Create a record in ServiceNow on pessoa table
  tags:
    - service-now
    - vijays-embedded-services
spec:
  owner: rhdh
  type: service
  

parameters:
  - title: Provide Name Entry for snow table
    required:
      - snowName
    properties:
      snowName:
        title: Requester Name
        type: string
        
  steps:
    - id: snowCreate
      name: Snow
      action: servicenow:now:table:createRecord
      input:
        tableName: u_pessoa
        requestBody: {
             u_namename: "${{ parameters.snowName }}"
         }

  output:
    text:
    - title: More information
      content: |
        **Results** `${{ steps['snowCreate'].output.sysid }}` You Entered Name : "${{ parameters.snowName }}"
